// YOU CANNOT MODIFY THIS FILE
var events = [{
        "start": 1550617765,
        "max2sec": 22.25,
        "board": "FoilT-80",
        "max10sec": 20.06,
        "desc": "Sailing in February.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 16.95,
        "end": 1550624691
    },
    {
        "start": 1552511533,
        "max2sec": 18.76,
        "board": "FoilT-80",
        "max10sec": 18.04,
        "desc": "Got up on foil a few times but the wind was dying and mostly slogged.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 8.03,
        "end": 1552518173
    },
    {
        "start": 1553205482,
        "max2sec": 23,
        "board": "FoilT-80",
        "max10sec": 22.46,
        "desc": "Good day for the 7.7 never needed to pump. Got a bit windy at times but never too extreme. Adjusted mast track to 41.0 inches which might have been a bit to far back. Lots of downwind practice and some confused chop up new TI made for a challenge.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 17.9,
        "end": 1553210543
    },
    {
        "start": 1553375921,
        "max2sec": 21.75,
        "board": "FoilT-80",
        "max10sec": 21.11,
        "desc": "Good windy day. Wind lasted longer than I could. A trip to TI and powered up down wind back.  A few falls. Need more stamina! Getting back in shape.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 20.68,
        "end": 1553382272
    },
    {
        "start": 1553723671,
        "max2sec": 23.68,
        "board": "FoilT-80",
        "max10sec": 23.47,
        "desc": "Low tide day so had to launch from BYC. Up and down winds, but in general a nice 5.9 day, though a bit light coming downwind. Good practice and one very nice tack where I was \"locked\" in and making good upwind speed.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 19.98,
        "end": 1553729883
    },
    {
        "start": 1553899195,
        "max2sec": 24.6,
        "board": "FoilT-80",
        "max10sec": 23.97,
        "desc": "Light 7.7 day but found the wind and had fun! Really had to pump it up onto a foil at times. Had to launch from BYC, discovered later that it was windier on the south side of the pier. This helped we get back without too much slogging.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 21.44,
        "end": 1553905788
    },
    {
        "start": 1553982789,
        "max2sec": 23.06,
        "board": "FoilT-80",
        "max10sec": 22.64,
        "desc": "Seemed windy but decreased by the time I hit the water. Took some work to get up on foil then get up wind. Then had nice sailing. A total of seven foilers out sailing. Beautiful day. ",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 24.25,
        "end": 1553990168
    },
    {
        "start": 1554846661,
        "max2sec": 23.86,
        "board": "Wave",
        "max10sec": 22.73,
        "desc": "First day back on the wave board. Took over half an hour to remember how to sail it. Very windy and gusty.  Quite a workout!",
        "sail": "5.0",
        "location": "Third Ave",
        "distance": 16.86,
        "end": 1554851890
    },
    {
        "start": 1555020671,
        "max2sec": 22.38,
        "board": "Wave",
        "max10sec": 20.8,
        "desc": "Windy, survival sailing. Average wind 30mph, gust to 35mph and some to 40mph. Though sometimes it was the lulls that zapped my strength with the waveboard. Getting used to the waveboard again and tunning it. In particular mast track position is critical.",
        "sail": "4.5",
        "location": "Third Ave",
        "distance": 14.49,
        "end": 1555025398
    },
    {
        "start": 1555192749,
        "max2sec": 24.02,
        "board": "FoilT-80",
        "max10sec": 23.51,
        "desc": "Started light for the 6.6 then came up. Very low tide so stayed on the North side of the pier most of the time until the wind really came up.  Nice day, but rough confused waves and chop up new TI.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 22.68,
        "end": 1555199287
    },
    {
        "start": 1555537166,
        "max2sec": 24.56,
        "board": "FoilT-80",
        "max10sec": 24.09,
        "desc": "Excellent day. Right call on the 7.7, got windy at times but also got light. Especially up near R2 when I decided not to follow Mike and Steve up to Alcatraz.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 27.75,
        "end": 1555544601
    },
    {
        "start": 1555794659,
        "max2sec": 23.82,
        "board": "FoilT-80",
        "max10sec": 22.26,
        "desc": "Start with the 5.9 but it was too much, 5.1 wasn't much better. Very gusty so very hard to get in the groove. Mostly just survival sailing. Should have taken the wave board.",
        "sail": "5.1",
        "location": "Berkeley",
        "distance": 8.98,
        "end": 1555800025
    },
    {
        "start": 1556142839,
        "max2sec": 24.26,
        "board": "FoilT-80",
        "max10sec": 23.93,
        "desc": "Interesting day, very hot inland, wind was doing the \"banding\" thing with periods of strong winds interspersed with near zero wind. Took a while to get far enough upwind to get consistent wind then it was pretty good. Some nice swells/waves when coming downwind made for fun sailing. GPS unit ran out of charge. One trip to Treasure Island and some sailing very close to the bay bridge.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 20,
        "end": 1556148701
    },
    {
        "start": 1556228700,
        "max2sec": 24,
        "board": "FoilT-80",
        "max10sec": 0,
        "desc": "GPS malfunction no track but basic trip info. Good 5.9 session! Had to launch from BYC due to low tide. Had five foilers out. Gusty but the 5.9 was the right pick. Had good wind all the way into to the harbor. Beautiful day on the bay.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 25.2,
        "end": 1556235900
    },
    {
        "start": 1556400082,
        "max2sec": 24.61,
        "board": "FoilT-80",
        "max10sec": 23.87,
        "desc": "Good 5.9 day. Low tides so launched at BYC. Two trips to Treasure Island and more. Look at that mileage.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 29.52,
        "end": 1556407707
    },
    {
        "start": 1556659901,
        "max2sec": 24.76,
        "board": "FoilT-80",
        "max10sec": 24.29,
        "desc": "Great day! Right sail choice. One trip to Treasure Island, one trip to R2 chasing after Mike and some fun sailing in the Olympic circle to get warmed up.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 31.42,
        "end": 1556667809
    },
    {
        "start": 1556918126,
        "max2sec": 23.73,
        "board": "FoilT-80",
        "max10sec": 23.04,
        "desc": "Miss-read my own tide tables, looked at the wrong month. Fine going out but mud coming in. Good wind but gusty for the 6.6 should have used the 5.9. Went over close to the bridge for some lighter wind.  Lots of mileage.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 31.37,
        "end": 1556925768
    },
    {
        "start": 1557089760,
        "max2sec": 24.08,
        "board": "FoilT-80",
        "max10sec": 23.47,
        "desc": "Good 5.9 day. Hit the water before 2PM. A couple trips to TI with other sailors. ",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 29.19,
        "end": 1557097777
    },
    {
        "start": 1557350969,
        "max2sec": 24.24,
        "board": "FoilT-80",
        "max10sec": 23.82,
        "desc": "Good day but very gusty. A couple of trips to Treasure Island. Some very confused chop.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 31.22,
        "end": 1557358736
    },
    {
        "start": 1557521522,
        "max2sec": 22.49,
        "board": "FoilT-80",
        "max10sec": 22.15,
        "desc": "A gusty windy day. Gusts 25-30mph, average 23-25mph, lulls 17-21. Trying to learn how to work with the 5.1. Added a downhaul setting. It seems that too much outhaul makes things too twitchy and \"catchy\". Seemed to have more trouble upwind than down. Quite a workout but more successful than the first time using the 5.1.",
        "sail": "5.1",
        "location": "Berkeley",
        "distance": 19.13,
        "end": 1557527195
    },
    {
        "start": 1557697027,
        "max2sec": 23.87,
        "board": "FoilT-80",
        "max10sec": 23.18,
        "desc": "A very gusty day. A bit less extreme than the previous Friday. Felt a bit more in tune with the 5.1. Shorter session since I had done a bunch of yard work and a bit lower on energy.",
        "sail": "5.1",
        "location": "Berkeley",
        "distance": 17.89,
        "end": 1557702625
    },
    {
        "start": 1557868760,
        "max2sec": 23.69,
        "board": "FoilT-80",
        "max10sec": 23.38,
        "desc": "Windy when I rigged but then came down a bunch but I managed to get out and up wind where I was able to \"ghost\" around. In the gusts was able to make progress up wind and close to R4. Then headed over and rounded R2. Then things got light so started back. Was able to get most of the way back without slogging. Turned out to be a nice day, though it was overcast the entire time.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 25.45,
        "end": 1557875849
    },
    {
        "start": 1559080448,
        "max2sec": 26.8,
        "board": "FoilT-80",
        "max10sec": 23.42,
        "desc": "First day back sailing in two weeks. Low tides so launched from BYC. Windy and gusty but pretty good considering how out of shape I got. One trip to Treasure Island and a fair amount of cruising around.",
        "sail": "6.9",
        "location": "Berkeley",
        "distance": 20.78,
        "end": 1559086659
    },
    {
        "start": 1560290958,
        "max2sec": 21.87,
        "board": "FoilT-80",
        "max10sec": 21.05,
        "desc": "Very light, got on a plane then slogging around for quite a while. It was 85 degrees at Berkeley used summer wetsuit on lower half of body and rash guard on the top. This kind of worked. Found some wind as I kept heading up. Got past the top of the pier then saw Mike P. coming back down with a broken foil so followed him down. Then the wind really kicked in so it was time to call it a day.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 18.89,
        "end": 1560299300
    },
    {
        "start": 1560462073,
        "max2sec": 21.71,
        "board": "FoilT-80",
        "max10sec": 20.88,
        "desc": "Windy, gusty day. I was much better on port tack up wind than on starboard. Went to south side of pier for a bit lighter winds and smoother waves.  Good high wind practice.",
        "sail": "5.1",
        "location": "Berkeley",
        "distance": 18.19,
        "end": 1560468188
    },
    {
        "start": 1560721887,
        "max2sec": 25.22,
        "board": "FoilT-80",
        "max10sec": 24.54,
        "desc": "Great 6.6 day. Problems with parking in the south basin, but great tides and good wind. Wind got light but was able to foil in to the docks! Nice to be back on the water.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 22.03,
        "end": 1560728173
    },
    {
        "start": 1560980151,
        "max2sec": 23.58,
        "board": "FoilT-80",
        "max10sec": 23.01,
        "desc": "Great 5.9 day. Rough chop and big waves but the foil really helped calm things down. A trip to Treasure Island and then a trip to R4 and R2.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 29.01,
        "end": 1560987253
    },
    {
        "start": 1561154400,
        "max2sec": 26.3,
        "board": "FoilT-80",
        "max10sec": 0,
        "desc": "GPS unit glitch so no track, but did get mileage and max speed. Rigged 5.9 then it backed off a bit but went with it and stayed where the wind was. Two trips to TI. Came back the last time on the north side of the pier to get more wind. Great sailing.",
        "sail": "5.9",
        "location": "Bekeley",
        "distance": 30.2,
        "end": 1561161600
    },
    {
        "start": 1561327935,
        "max2sec": 24.01,
        "board": "FoilT-80",
        "max10sec": 23.33,
        "desc": "Late start. Was very windy then came down. The 5.9 was the right choice. One trip to TI and some fun cruising. Big waves and chop.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 17.31,
        "end": 1561332887
    },
    {
        "start": 1561585224,
        "max2sec": 25.79,
        "board": "FoilT-80",
        "max10sec": 25.05,
        "desc": "Windy but unusual. Low tides so launched from yacht club. Windier at Berkeley than at Treasure Island. In fact on the first trip to TI it got kind of light, but it was still very windy when I went down to Berkeley. Did another trip up and such. Some smoother water at times and some big swells.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 30.08,
        "end": 1561592787
    },
    {
        "start": 1561758800,
        "max2sec": 25.05,
        "board": "FoilT-80",
        "max10sec": 24.71,
        "desc": "Windy and gusty. Three or so trips up to Treasure Island. Chased after different folks at different times. Challenging day with some very good runs.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 35.53,
        "end": 1561767568
    },
    {
        "start": 1561930629,
        "max2sec": 24.55,
        "board": "FoilT-80",
        "max10sec": 23.94,
        "desc": "Turned into a light 5.9 day. Thought it was going to be windier, but managed to get out. Went to the north of the pier to find more wind. Otherwise another good day.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 30.99,
        "end": 1561939213
    },
    {
        "start": 1562365884,
        "max2sec": 23.26,
        "board": "FoilT-80",
        "max10sec": 22.73,
        "desc": "Late start. Mostly mellow 6.6 day. Light at times. Pretty day on the bay. Summer wetsuit and such.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 25.61,
        "end": 1562373169
    },
    {
        "start": 1562536099,
        "max2sec": 23.9,
        "board": "FoilT-80",
        "max10sec": 23.39,
        "desc": "Light 7.7 day. It was supposed to be much windier, but managed to get out and rack up one trip to TI. Strange that a 7.7 now feels big. Over wise a nice summer day on the bay.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 18.5,
        "end": 1562543380
    },
    {
        "start": 1562709193,
        "max2sec": 18.24,
        "board": "Surfboard",
        "max10sec": 16.68,
        "desc": "First GPS tracks of delta kiting. Was the wind dummy and setup the 15 which was good initially, the wind continued to increase and got to the point where the depowering of the kite was making the kite hard to steer so changed down to the 11. Was surprised that I could stay on the strapless surfboard in the sizeable chop. Learning the concept of toe-side and carved jibes but wasn't close.",
        "sail": "15, 11 (kite)",
        "location": "Sherman Island",
        "distance": 14.87,
        "end": 1562717754
    },
    {
        "start": 1562882672,
        "max2sec": 24.24,
        "board": "FoilT-80",
        "max10sec": 23.54,
        "desc": "Windy and gusty 5.9 day. Better and windier on the north side of pier. Tried coming down on the south side after the first trip to TI but it got too light. Big waves. Quite a workout, but nice to be on such a small sail!",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 25.42,
        "end": 1562890078
    },
    {
        "start": 1563058200,
        "max2sec": 0,
        "board": "FoilT-80",
        "max10sec": 0,
        "desc": "Forgot both GPS units! Light down in south basin, tide was just a bit too low so I had to walk board out a bit through the mud. Took 20-30 minutes to get up to the wind line, and needed to get over to the north side of pier for consistent wind. One trip to treasure island. Windy and gusty up there. Tried coming down south of the pier but too light so went back over the top of the pier and down the north side.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 0,
        "end": 1563064200
    },
    {
        "start": 1563314948,
        "max2sec": 19.27,
        "board": "Twin-Tip151",
        "max10sec": 16.73,
        "desc": "Full range of wind conditions, the 11m was good most of the time till things got real light. Strong flood so had to work to get upwind. Started learning some toeside riding and carved jibes.",
        "sail": "11 (kite)",
        "location": "Sherman Island",
        "distance": 16.66,
        "end": 1563321696
    },
    {
        "start": 1563486026,
        "max2sec": 23.07,
        "board": "FoilT-80",
        "max10sec": 22.38,
        "desc": "Light down in the basin, was able to get out and up, then it got light up there so went over to the north side of the pier, but it was still light so kept heading north finally found some wind. Went far enough north that I was able to make it to TI on the next starboard tack.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 21.49,
        "end": 1563493029
    },
    {
        "start": 1563655894,
        "max2sec": 25.52,
        "board": "FoilT-80",
        "max10sec": 25.22,
        "desc": "Thought it was going to be windier so went with the 6.6. Was able to get up wind but had to search for the wind. Was trying to go around Alcatraz but the wind got too light near the top of Angel Island. Did some nice runs over towards the city front.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 29.35,
        "end": 1563663103
    },
    {
        "start": 1563743053,
        "max2sec": 25.17,
        "board": "FoilT-80",
        "max10sec": 24.74,
        "desc": "More wind than yesterday. This time was able to get up and around Alcatraz, then it got light but was able to ghost down on foil til found more wind closer to Berkeley. Racked up a few more mellow miles and called it a day.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 32.93,
        "end": 1563750251
    },
    {
        "start": 1563925243,
        "max2sec": 19.79,
        "board": "Twin Tip",
        "max10sec": 18.91,
        "desc": "Forgot to turn on the GPS till halfway through the lesson. Kited with Sandy and explored the delta a bit. Full range of wind conditions. Slack and then flood tides.",
        "sail": "13 (kite)",
        "location": "Sherman Island",
        "distance": 12.56,
        "end": 1563930272
    },
    {
        "start": 1564093141,
        "max2sec": 23.62,
        "board": "FoilT-80",
        "max10sec": 23.24,
        "desc": "Started strong but sailed into weeds at Ashby shoal and got weeds wrapped around foil in a hard to get off way. Finally jumped in and flipped the board over to clear.  Forgot camelback so was thirsty. Full range of wind conditions. Windy at Treasure so didn't venture further up. Got becalmed heading home on the last trip down, but a puff came through and got me moving again and foiled to the dock.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 27.32,
        "end": 1564099961
    },
    {
        "start": 1564179065,
        "max2sec": 24.17,
        "board": "FoilT-80",
        "max10sec": 23.88,
        "desc": "Full range of conditions. From smooth to nasty chop, to nice rollers.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 32.05,
        "end": 1564186498
    },
    {
        "start": 1564528423,
        "max2sec": 17.92,
        "board": "Twin tip 151",
        "max10sec": 16.98,
        "desc": "Started a bit light for the 11m. Used a new wider twin tip at first. Liked the old one better and switched back. Wind gust to about 22mph and lulls sometimes below 15mph, averaging around 18mph. These are based on Sherman M12 readings. A lot of work on toe-side riding with a fair amount of success including jibes! Trouble with light winds and flood tide initially but by the end the wind improved and flood went to slack. Forgot again to turn on GPS until had already been kiting a while.",
        "sail": "11m (kite)",
        "location": "Sherman Island",
        "distance": 18.6,
        "end": 1564535789
    },
    {
        "start": 1564697527,
        "max2sec": 23.72,
        "board": "FoilT-80",
        "max10sec": 22.88,
        "desc": "Oscillating winds. Went with a 6.6 since the gusts at TI were strong. But took quite a while to get out with near zero lulls. At the end things kicked in and was overpowered at times. Very unstable winds with lots of shifts as well.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 20.36,
        "end": 1564704234
    },
    {
        "start": 1564955623,
        "max2sec": 23.11,
        "board": "FoilT-80",
        "max10sec": 22.57,
        "desc": "Another challenging wind day. A bit easier than Thursday to get out but variable and shifty. Very confused chop and waves at times. At times very windy near the top of the pier/TI.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 23.02,
        "end": 1564962291
    },
    {
        "start": 1565131180,
        "max2sec": 20.7,
        "board": "151 Twintip",
        "max10sec": 20.38,
        "desc": "Had ebb tide and slack water most of the time so easy to be upwind. Got to explore the range of the 13m since it was fairly light but with some windier periods. Found some smoother water and worked a lot on toeside manuevers and jibes. Forgot to turn on the GPS again, and somehow pressed a button and turned it off before finishing. Wind averaged under 20mph the whole time, peak gusts around 22mph, lulls down to 12 or 13mph.",
        "sail": "13m (kite)",
        "location": "Sherman Island",
        "distance": 16.44,
        "end": 1565136132
    },
    {
        "start": 1565302928,
        "max2sec": 22.95,
        "board": "FoilT-80",
        "max10sec": 22.24,
        "desc": "Windy and gusty. Most of the time too windy. First time on the new 5.5. Too gusty to properly evaluate. Quite a workout. It backed off a bit at the end and was able to have some relatively decent runs up and down but not going too high up the pier. For a bit, when not overpowered downwind, there were some big rollers (waves) to play with.",
        "sail": "5.5",
        "location": "Berkeley",
        "distance": 17.62,
        "end": 1565307820
    },
    {
        "start": 1565476326,
        "max2sec": 23.62,
        "board": "FoilT-80",
        "max10sec": 22.74,
        "desc": "Crazy wind day and tide just a bit too low so had to walk things out. Light inside and very southerly. Took a while to get out and up. Then it really kicked in and was overpowered on the 6.6. Made my way over towards the bridge for a bit of relief. Due to the flood the chop wasn't as bad as it would have been for all that wind. Big rollers. One trip to treasure island. Wind was less gusty up there. On the way back down had some fun surfing the rollers. Down closer to Berkeley it got very gusty again. Then at the end the wind started going in circles making the last little bit to get in a real pain.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 15.01,
        "end": 1565482109
    },
    {
        "start": 1566336607,
        "max2sec": 22.57,
        "board": "FoilT-80",
        "max10sec": 22.03,
        "desc": "Windy and wild 5.9 day. Two trips to Treasure Island and I was done. Ugly chop a lot of the time. Gusty too.",
        "sail": "5.9",
        "location": " Berkeley",
        "distance": 23.42,
        "end": 1566342022
    },
    {
        "start": 1566770443,
        "max2sec": 23.07,
        "board": "FoilT-80",
        "max10sec": 21.96,
        "desc": "Forgot to turn on the GPS again! Was probably out for 20-30 minutes. Windy and gusty 6.6 day with large waves. Challenging but fun when not too overpowered.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 19.97,
        "end": 1566774968
    },
    {
        "start": 1566937567,
        "max2sec": 23.98,
        "board": "FoilT-80",
        "max10sec": 23.51,
        "desc": "Nice early start. Wind forecasts have been poor so went once I saw the wind blowing. Good 6.6 day. Started trying foil jibes. Didn't get any. Also worked on being on foil without being in footstraps.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 25.61,
        "end": 1566943834
    },
    {
        "start": 1567034167,
        "max2sec": 19.32,
        "board": "TwinTip151",
        "max10sec": 17.95,
        "desc": "Windy! Average around 25 mph at start so use Kitopia's 9m rather than my 11. Flood turned to ebb so not much problem staying up wind. Good practice with higher winds. More toeside and jibe practice.",
        "sail": "9 (kite)",
        "location": "Sherman Island",
        "distance": 16,
        "end": 1567042282
    },
    {
        "start": 1567289977,
        "max2sec": 21.89,
        "board": "FoilT-80",
        "max10sec": 21.32,
        "desc": "Started out as a nice 6.6 day. On the way back down from Treasure Island the bolts in the foil pulled through the board (either hit a fish or stress coming down a wave). Managed not to lose the foil. But very slow going to get in so took a ride from the nice folks at Cal Adventures.  A bunch of board repair stuff to do.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 16.38,
        "end": 1567296094
    },
    {
        "start": 1567445400,
        "max2sec": 0,
        "board": "Twintip",
        "max10sec": 0,
        "desc": "Forgot GPS watch. Was mainly going out to get Leland a kite lesson, but had good tides and just enough wind for the 13. Had a nice little session while Leland was doing his land training.",
        "sail": "13 (kite)",
        "location": "Sherman Island",
        "distance": 0,
        "end": 1567449000
    },
    {
        "start": 1567887243,
        "max2sec": 23.71,
        "board": "FoilT-80",
        "max10sec": 23.37,
        "desc": "Testing out repairs and seeing if the fin box would hold. Used really big washers like I use to use on my ML10. Foil seemed not to move and fin box held. Hit the water nice and early though I had to wait a while to get a parking place. Wind was good early. Got very gusty at the end.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 27.85,
        "end": 1567894160
    },
    {
        "start": 1568066359,
        "max2sec": 22.83,
        "board": "FoilT-80",
        "max10sec": 22.31,
        "desc": "Gusty and in bands. Good day for the 5.9 only over powered for short times and never under powered. Fun waves to play with coming down wind. Still trying to get a foiling jibe...",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 27.38,
        "end": 1568073385
    },
    {
        "start": 1568416656,
        "max2sec": 23.64,
        "board": "FoilT-80",
        "max10sec": 23.3,
        "desc": "Wind came up late. Just enough to sail. One trip almost to TI but the wind got too light up there so came down and stayed in the Olympic circle particularly a bit North had better wind.",
        "sail": "7.7",
        "location": "Berkeley",
        "distance": 21.92,
        "end": 1568422572
    },
    {
        "start": 1568503463,
        "max2sec": 23.78,
        "board": "FoilT-80",
        "max10sec": 23.47,
        "desc": "Late start. Cal Cup racers were finishing up and coming in. Windy and gusty. Good for 6.6. Launched from BYC. Stayed north of the pier in case of issues with board or the wind.  Good idea the wind did shut down. But not too much slogging.",
        "sail": "6.6",
        "location": "",
        "distance": 18.57,
        "end": 1568508925
    },
    {
        "start": 1568756080,
        "max2sec": 23.87,
        "board": "FoilT-80",
        "max10sec": 23.63,
        "desc": "Nice high tides, but the gates to the parking lot were locked so had to launch from BYC. Argh.  Mellow 6.6 wind to start. Sailed up a ways then came back down and found Jim, then we headed to TI. Got a bit too light for Jim, I kept going and the wind improved. Thought I saw Steve heading to Alcatraz so headed up myself and the conditions were good for a rounding! Though rough and confused waves/chop above Alcatraz.  Lots of distance with some fun too!",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 28.03,
        "end": 1568763148
    },
    {
        "start": 1569103303,
        "max2sec": 24.48,
        "board": "FoilT-80",
        "max10sec": 23.85,
        "desc": "Quick session. Good 6.6 day. Got a bit light up near Treasure Island so came back down. Better wind down low.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 22.81,
        "end": 1569108786
    },
    {
        "start": 1569363970,
        "max2sec": 22.74,
        "board": "FoilT-80",
        "max10sec": 22.35,
        "desc": "Probably should have gone with a bigger sail but was okay until 5PM when it died. Had a moderate length slog back in.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 24.15,
        "end": 1569371963
    },
    {
        "start": 1569791572,
        "max2sec": 23.23,
        "board": "FoilT-80",
        "max10sec": 22.96,
        "desc": "Windy and gusty. Two trips to Treasure Island. In addition to the sizeable chop a lot of crazy boat wakes.",
        "sail": "5.9",
        "location": "Berkeley",
        "distance": 24.31,
        "end": 1569797397
    },
    {
        "start": 1569966406,
        "max2sec": 22.35,
        "board": "FoilT-80",
        "max10sec": 21.88,
        "desc": "Seemed windy so rigged the 6.6, then it seemed to back off. Had to work hard to get on foil. Lots of pumping. Finally found the wind and chased some folks around. Went to Treasure Island then out towards Angel Island and R2.  Wind held all the way back to Berkeley. Got a foiling jibe! But it was somewhat a fluke since I wasn't able to repeat it. Spent time practicing being on foil without footstraps.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 26.16,
        "end": 1569972788
    },
    {
        "start": 1571350656,
        "max2sec": 22.5,
        "board": "FoilT-80",
        "max10sec": 21.3,
        "desc": "Northwesterly wind. Started really light then eventually turned on. Left from BYC since no wind in the south basin despite high tides. Very weird waves due to wind direction. Eventually too much wind for the 6.6.",
        "sail": "6.6",
        "location": "Berkeley",
        "distance": 14.35,
        "end": 1571355147
    },
    {
        "start": 1577685301,
        "max2sec": 15.27,
        "board": "TwinTip 137cm",
        "max10sec": 13.49,
        "desc": "Took a \"lesson\" south of Perth in Western Australia.  Good winds, beach setup and launch. Used all my gear except for the board. Strange getting used to wind and waves from different angles than I was used to. Very nice site for intermediate learning. Has waves and chop so would not be good for complete beginner.",
        "sail": "11 Kite",
        "location": "Woodman Pt, WA",
        "distance": 8.15,
        "end": 1577694262
    }
];